### ISSUE TITLE
Sync Beat works only the first time is enabled

### ISSUE THREAD

**Issue by crshrprt** [ardura/Scrollscope#9]
Thank you for this plugin, to my knowledge is the first FLOSS oscilloscope with Sync Beat that runs natively on Linux. :)

When I activate the Sync Beat option the first time since I open the plugin UI it works and the sounds are drawn on the oscilloscope.
If I disable Sync Beat option and enable it again the oscilloscope remain empty, no sounds are drawn.
With Sync Beat disabled sounds are drawn normally.

**Comment by ardura** [comment]
Should be fixed in latest update :)

**Comment by crshrprt** [comment]
I still have the same problem. I tried to build the plugin from scratch with the latest commit, just to make sure I wasn't using an old version, but Sync Beat will work only the first time is enabled. Here's a video of showing the issue:

https://github.com/ardura/Scrollscope/assets/114294020/bfce9310-ce0f-4df4-8704-bb5e7525914c

**Comment by ardura** [comment]
I'll try downloading Ardour and see if I have the same issue. That's a weird one then.

**Comment by crshrprt** [comment]
I tried in BespokeSynth (same problem) and Carla (it crashes the host as soon Sync Beat is enabled) too.

**Comment by ardura** [comment]
Can you try with this branch? There's some juttering in Ardour but it works enough to reference. Use the Alt Sync checkbox + beat sync. Seems like the timeline is just counted differently in different DAWs unfortunately.
https://github.com/ardura/Scrollscope/tree/fixing-sync-other-daws

**Comment by crshrprt** [comment]
Thank you, I can confirm the Alt Sync fixes the problem. :)

There is indeed a bit of jitter in Ardour, while in BespokeSynth there isn't.
